version: 2
jobs:
  build:
    docker:
    - image: jjcg/sq-base:00
      #user: sonarqube
    steps:
    - checkout
    - run:
        name: test
        command: |
          whoami
          PATH=$PATH:/opt/jdk-minimal/bin/
          mv /opt/jdk-minimal  /opt/java
          ls -l /opt/java
          PATH=$PATH:/opt/java/bin/
          java -version
    - run:
        name: sys update
        command: apt-get update
    - run:
        name: sys update
        command: apt-get upgrade -y
    - run:
        name: install packages
        command:  apt-get install -y unzip wget procps software-properties-common unzip wget apt-utils vim nginx supervisor libpq-dev libjpeg-dev screen tmux man build-essential
    - run:
        name: Install Sonarqube
        command: |
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.8.zip
          ls -l /opt/
          mkdir -p /opt/sonarqube-7.8
          unzip ./sonarqube-7.8.zip
          cp -a ./sonarqube-7.8/.  /opt/sonarqube-7.8/
          ls /opt
          chown -R root:root /opt/sonarqube-7.8/
          cp -rf ./sonarFiles/bin/linux-x86-64/sonar.sh /opt/sonarqube-7.8/bin/linux-x86-64/
          cp -rf ./sonarFiles/conf/wrapper.conf /opt/sonarqube-7.8/conf/
          cp -rf ./sonarFiles/etc/systemd/system/sonar.service /etc/systemd/system/sonar.service
    - run:
        name: Run Sonarqube
        command: |
          ls -l /opt/
          ls -l /opt/sonarqube-7.8/
          ls -l /opt/sonarqube-7.8/bin/linux-x86-64/
          ls -l /opt/sonarqube-7.8/conf/
          #adduser --disabled-password --disabled-login --gecos GECOS  sonarqube
          ls -l /opt/sonarqube-7.8/
          #su sonarqube
          whoami
          cat /opt/sonarqube-7.8/bin/linux-x86-64/sonar.sh
          cat /opt/sonarqube-7.8/conf/wrapper.conf
          cat /etc/systemd/system/sonar.service
          #/bin/bash /opt/sonarqube-7.8/bin/linux-x86-64/sonar.sh status
          sudo systemctl start sonar
          sudo systemctl enable sonar
          sudo systemctl status sonar
    - run:
        name: shell
        command: |
          /bin/bash

#    - run:
#        name: Install Sonarqube scanner
#        command: |
#          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
#            unzip sonar-scanner-cli-4.0.0.1744-linux.zip
#    - run:
#        name: Run Sonarqube scanner
#        command: |
#          eval ./sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner -Dsonar.projectKey=${CIRCLE_PROJECT_REPONAME} \
#          -Dsonar.projectVersion=${CIRCLE_BRANCH} \
#          -Dsonar.host.url=http://54.160.99.9:9000 \
#          -Dsonar.login=81948a1dfc757648fa3b92b8a513ec0a6e03e947

