version: 2
jobs:
  build:
    docker:
    - image: debian:latest
    steps:
    - checkout
    - run:
        name: Prin sys info
        command: cat /etc/os-release
    - run:
        name: sys update
        command: apt-get update
    - run:
        name: sys update
        command: apt-get upgrade -y
    - run:
        name: install packages
        command:  apt-get install -y  wget apt-utils vim nginx supervisor libpq-dev libjpeg-dev screen tmux man build-essential
    - run:
        name: Install Sonarqube scanner
        command: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
          unzip sonar-scanner-cli-4.0.0.1744-linux.zip

