version: 2
jobs:
  build:
    docker:
    - image: debian:latest
    steps:
    - checkout
    - run:
        name: Prin sys info
        command: cat /etc/os-release
    - run:
        name: print network  info
        command: ifconfig

