version: 2
jobs:
  build:
    docker:
    - image: jjcg/sq-base:00
    steps:
    - checkout
    - run:
        name: test
        command: ls /opt/
    - run:
        name: sys update
        command: apt-get update
    - run:
        name: sys update
        command: apt-get upgrade -y
    - run:
        name: install packages
        command:  apt-get install -y procps software-properties-common unzip wget apt-utils vim nginx supervisor libpq-dev libjpeg-dev screen tmux man build-essential

