version: 2
jobs:
  build:
    docker:
    - image: jjcg/sq-base:00
    steps:
    - checkout
    - run:
        name: test
        command: |
          PATH=$PATH:/opt/jdk-minimal/bin/
          java -version
    - run:
        name: sys update
        command: apt-get update
    - run:
        name: sys update
        command: apt-get upgrade -y
    - run:
        name: install packages
        command:  apt-get install -y unzip wget procps software-properties-common unzip wget apt-utils vim nginx supervisor libpq-dev libjpeg-dev screen tmux man build-essential
    - run:
        name: Install Sonarqube
        command: |
          wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-7.8.zip
          unzip sonarqube-7.8.zip
    - run:
        name: Run Sonarqube
        command: |
          pwd
          ./sonarqube-7.8/bin/linux-x86-64/sonar.sh -Dwrapper.java.command=/opt/jdk-minimal/bin/ status

